### ISSUE TITLE
No Blinking of the Tracker if WiFi Window is open / WiFi Window does not show anything if i set the WiFi / Amazon Trackers setting the WiFi 

### ISSUE THREAD

**Issue by artempub** [artempub/pytorch-pommerman#2]
Problems:

Some user report that they can not use the WiFi window to set the WiFi credentials. (Hard coding works)
Some user report that the Tracker stops working if plugged in and they open the WiFi window on the Server
Affected hardware (to my knowledge):

some Amazon Trackers
some D1 Mini with CH340c or g USB to Serial chip-sets. (That what i remember from supports)
Workaround:

Setting up the full Development, And use the workaround:
https://discord.com/channels/817184208525983775/878727840118505533/977740333955821599
Root cause:

RTS and DTR are used on development boards for Flash Mode and for Reset. But that seems not always to be the same.
Sometimes they change the state when open the serial connection.
Solution:

to be defined.
Dangers:

Resting the wrong device (3d Printer,... ) if used on the wrong device.
Open Pull request:

Allow the user to use change the RTS and DTR to what they like, so they do not need to install everything:
Added SerialSetCtrlRequest SolarXR-Protocol#21
Adding Serial RTS / DTR control elements #186
Missing:

Good description, Advanced Setting
New UI integration
Help Content
Testing on different devices

**Comment by davronverse** [comment]
After some more writing,
On the most boards it seems to work when RTS and DTR are set to 0.
Windows seems to default them to 1. it seems some boards do not work that way.

Setting them to 0 by default on our application could help. But the samples i have are too small to be sure that it works in every case.
So i would love to have the option for the user to change this lines. It also gives the possibility to reset the d1 mini from the software to see the full log.
Maybe a survey after the release or a request for feedback would be great to get samples?
